-- Rollback de 0044_catalogo_semilla_productos.sql
--
-- Borra únicamente las filas que coincidan EXACTAMENTE (los 5 campos) con la
-- semilla insertada — nunca toca una fila con el mismo nombre/categoría que
-- haya sido editada después (por curaduría o desde el Maestro de productos),
-- ni una fila que la migración original haya saltado por WHERE NOT EXISTS.

delete from productos_maestro pm
using (values
  ('Coca-Cola 250ml', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 250ml'),
  ('Coca-Cola 400ml', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 400ml'),
  ('Coca-Cola 1.5L', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 1.5L'),
  ('Coca-Cola 2L', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 2L'),
  ('Coca-Cola 3L', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 3L'),
  ('Coca-Cola Zero 400ml', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 400ml'),
  ('Coca-Cola Zero 1.5L', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 1.5L'),
  ('Coca-Cola Zero 2L', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 2L'),
  ('Coca-Cola Sin Azúcar 400ml', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 400ml'),
  ('Coca-Cola Sin Azúcar 1.5L', 'Bebidas', 'Coca-Cola', 'unidad', 'Botella 1.5L'),
  ('Sprite 400ml', 'Bebidas', 'Sprite', 'unidad', 'Botella 400ml'),
  ('Sprite 1.5L', 'Bebidas', 'Sprite', 'unidad', 'Botella 1.5L'),
  ('Sprite 2L', 'Bebidas', 'Sprite', 'unidad', 'Botella 2L'),
  ('Fanta Naranja 400ml', 'Bebidas', 'Fanta', 'unidad', 'Botella 400ml'),
  ('Fanta Naranja 1.5L', 'Bebidas', 'Fanta', 'unidad', 'Botella 1.5L'),
  ('Fanta Naranja 2L', 'Bebidas', 'Fanta', 'unidad', 'Botella 2L'),
  ('Quatro 400ml', 'Bebidas', 'Quatro', 'unidad', 'Botella 400ml'),
  ('Quatro 1.5L', 'Bebidas', 'Quatro', 'unidad', 'Botella 1.5L'),
  ('Postobón Colombiana 400ml', 'Bebidas', 'Postobón', 'unidad', 'Botella 400ml'),
  ('Postobón Colombiana 1.5L', 'Bebidas', 'Postobón', 'unidad', 'Botella 1.5L'),
  ('Postobón Colombiana 2L', 'Bebidas', 'Postobón', 'unidad', 'Botella 2L'),
  ('Postobón Colombiana 3L', 'Bebidas', 'Postobón', 'unidad', 'Botella 3L'),
  ('Postobón Manzana 400ml', 'Bebidas', 'Postobón', 'unidad', 'Botella 400ml'),
  ('Postobón Manzana 1.5L', 'Bebidas', 'Postobón', 'unidad', 'Botella 1.5L'),
  ('Postobón Manzana 2L', 'Bebidas', 'Postobón', 'unidad', 'Botella 2L'),
  ('Postobón Uva 400ml', 'Bebidas', 'Postobón', 'unidad', 'Botella 400ml'),
  ('Postobón Uva 1.5L', 'Bebidas', 'Postobón', 'unidad', 'Botella 1.5L'),
  ('Postobón Naranja 400ml', 'Bebidas', 'Postobón', 'unidad', 'Botella 400ml'),
  ('Postobón Naranja 1.5L', 'Bebidas', 'Postobón', 'unidad', 'Botella 1.5L'),
  ('Hipinto 400ml', 'Bebidas', 'Hipinto', 'unidad', 'Botella 400ml'),
  ('Hipinto 1.5L', 'Bebidas', 'Hipinto', 'unidad', 'Botella 1.5L'),
  ('Popular Soda 1.5L', 'Bebidas', 'Popular', 'unidad', 'Botella 1.5L'),
  ('Popular Soda 2L', 'Bebidas', 'Popular', 'unidad', 'Botella 2L'),
  ('Kola Román 400ml', 'Bebidas', 'Kola', 'unidad', 'Botella 400ml'),
  ('Kola Román 1.5L', 'Bebidas', 'Kola', 'unidad', 'Botella 1.5L'),
  ('Agua Tónica Postobón 400ml', 'Bebidas', 'Agua', 'unidad', 'Botella 400ml'),
  ('Ginger Ale Postobón 400ml', 'Bebidas', 'Ginger', 'unidad', 'Botella 400ml'),
  ('Ginger Ale Postobón 1.5L', 'Bebidas', 'Ginger', 'unidad', 'Botella 1.5L'),
  ('Cerveza Águila 330ml lata', 'Bebidas', 'Águila', 'unidad', '330ml lata'),
  ('Cerveza Águila 330ml botella', 'Bebidas', 'Águila', 'unidad', '330ml botella'),
  ('Cerveza Águila 750ml', 'Bebidas', 'Águila', 'unidad', '750ml'),
  ('Cerveza Águila Light 330ml lata', 'Bebidas', 'Águila', 'unidad', '330ml lata'),
  ('Cerveza Águila Light 330ml botella', 'Bebidas', 'Águila', 'unidad', '330ml botella'),
  ('Cerveza Poker 330ml lata', 'Bebidas', 'Poker', 'unidad', '330ml lata'),
  ('Cerveza Poker 330ml botella', 'Bebidas', 'Poker', 'unidad', '330ml botella'),
  ('Cerveza Poker 750ml', 'Bebidas', 'Poker', 'unidad', '750ml'),
  ('Cerveza Costeña 330ml botella', 'Bebidas', 'Costeña', 'unidad', '330ml botella'),
  ('Cerveza Costeña 750ml', 'Bebidas', 'Costeña', 'unidad', '750ml'),
  ('Cerveza Club Colombia Dorada 330ml botella', 'Bebidas', 'Club', 'unidad', '330ml botella'),
  ('Cerveza Club Colombia Roja 330ml botella', 'Bebidas', 'Club', 'unidad', '330ml botella'),
  ('Cerveza Club Colombia Negra 330ml botella', 'Bebidas', 'Club', 'unidad', '330ml botella'),
  ('Cerveza Pilsen 330ml botella', 'Bebidas', 'Pilsen', 'unidad', '330ml botella'),
  ('Cerveza Pilsen 750ml', 'Bebidas', 'Pilsen', 'unidad', '750ml'),
  ('Cerveza Redd''s 330ml botella', 'Bebidas', 'Redd''s', 'unidad', '330ml botella'),
  ('Cerveza Cerveza Andina 330ml lata', 'Bebidas', 'Cerveza', 'unidad', '330ml lata'),
  ('Cerveza Michelob Ultra 330ml botella', 'Bebidas', 'Michelob', 'unidad', '330ml botella'),
  ('Cerveza Corona 355ml botella', 'Bebidas', 'Corona', 'unidad', '355ml botella'),
  ('Cerveza Stella Artois 330ml botella', 'Bebidas', 'Stella', 'unidad', '330ml botella'),
  ('Pony Malta 354ml', 'Bebidas', 'Pony', 'unidad', '354ml'),
  ('Malta Leona 330ml', 'Bebidas', 'Malta', 'unidad', '330ml'),
  ('Malta Águila 330ml', 'Bebidas', 'Malta', 'unidad', '330ml'),
  ('Agua Cristal 300ml', 'Bebidas', 'Cristal', 'unidad', 'Botella 300ml'),
  ('Agua Cristal 600ml', 'Bebidas', 'Cristal', 'unidad', 'Botella 600ml'),
  ('Agua Cristal 1L', 'Bebidas', 'Cristal', 'unidad', 'Botella 1L'),
  ('Agua Cristal 3L', 'Bebidas', 'Cristal', 'unidad', 'Botella 3L'),
  ('Agua Cristal 6L', 'Bebidas', 'Cristal', 'unidad', 'Botella 6L'),
  ('Agua Manantial 600ml', 'Bebidas', 'Manantial', 'unidad', 'Botella 600ml'),
  ('Agua Manantial 1L', 'Bebidas', 'Manantial', 'unidad', 'Botella 1L'),
  ('Agua Brisa 600ml', 'Bebidas', 'Brisa', 'unidad', 'Botella 600ml'),
  ('Agua Brisa 1L', 'Bebidas', 'Brisa', 'unidad', 'Botella 1L'),
  ('Agua Brisa 3L', 'Bebidas', 'Brisa', 'unidad', 'Botella 3L'),
  ('Agua Oasis 600ml', 'Bebidas', 'Oasis', 'unidad', 'Botella 600ml'),
  ('Hit Naranja 200ml', 'Bebidas', 'Hit', 'unidad', '200ml'),
  ('Hit Naranja 400ml', 'Bebidas', 'Hit', 'unidad', '400ml'),
  ('Hit Naranja 1L', 'Bebidas', 'Hit', 'unidad', '1L'),
  ('Hit Mango 200ml', 'Bebidas', 'Hit', 'unidad', '200ml'),
  ('Hit Mango 400ml', 'Bebidas', 'Hit', 'unidad', '400ml'),
  ('Hit Mango 1L', 'Bebidas', 'Hit', 'unidad', '1L'),
  ('Hit Mora 200ml', 'Bebidas', 'Hit', 'unidad', '200ml'),
  ('Hit Mora 400ml', 'Bebidas', 'Hit', 'unidad', '400ml'),
  ('Hit Lulo 200ml', 'Bebidas', 'Hit', 'unidad', '200ml'),
  ('Hit Lulo 400ml', 'Bebidas', 'Hit', 'unidad', '400ml'),
  ('Del Valle Naranja 413ml', 'Bebidas', 'Del', 'unidad', '413ml'),
  ('Del Valle Mango 413ml', 'Bebidas', 'Del', 'unidad', '413ml'),
  ('Tutti Frutti 200ml', 'Bebidas', 'Tutti', 'unidad', '200ml'),
  ('Tutti Frutti 300ml', 'Bebidas', 'Tutti', 'unidad', '300ml'),
  ('Ades Soya 1L', 'Bebidas', 'Ades', 'unidad', '1L'),
  ('California Néctar Durazno 300ml', 'Bebidas', 'California', 'unidad', '300ml'),
  ('Jugo Natu Fruit 250ml', 'Bebidas', 'Jugo', 'unidad', '250ml'),
  ('Energizante Vive100 250ml', 'Bebidas', 'Vive100', 'unidad', '250ml'),
  ('Energizante Vive100 473ml', 'Bebidas', 'Vive100', 'unidad', '473ml'),
  ('Energizante Speed Max 269ml', 'Bebidas', 'Speed', 'unidad', '269ml'),
  ('Energizante Red Bull 250ml', 'Bebidas', 'Red', 'unidad', '250ml'),
  ('Energizante Peak 250ml', 'Bebidas', 'Peak', 'unidad', '250ml'),
  ('Té Lipton Frío Durazno 400ml', 'Bebidas', 'Lipton', 'unidad', '400ml'),
  ('Té Lipton Frío Limón 400ml', 'Bebidas', 'Lipton', 'unidad', '400ml'),
  ('Avena Alpina Bebible 200ml', 'Bebidas', 'Alpina', 'unidad', '200ml'),
  ('Yogo Yogo Fresa 200ml', 'Bebidas', 'Alpina', 'unidad', '200ml'),
  ('Gatorade Uva 500ml', 'Bebidas', 'Gatorade', 'unidad', '500ml'),
  ('Gatorade Naranja 500ml', 'Bebidas', 'Gatorade', 'unidad', '500ml'),
  ('Leche Alpina Entera 1.1L', 'Lácteos', 'Alpina', 'unidad', '1.1L'),
  ('Leche Alpina Entera 900ml', 'Lácteos', 'Alpina', 'unidad', '900ml'),
  ('Leche Alpina Entera 200ml', 'Lácteos', 'Alpina', 'unidad', '200ml'),
  ('Leche Alpina Deslactosada 1.1L', 'Lácteos', 'Alpina', 'unidad', '1.1L'),
  ('Leche Alquería Entera 1.1L', 'Lácteos', 'Alquería', 'unidad', '1.1L'),
  ('Leche Alquería Entera 900ml', 'Lácteos', 'Alquería', 'unidad', '900ml'),
  ('Leche Alquería Deslactosada 1.1L', 'Lácteos', 'Alquería', 'unidad', '1.1L'),
  ('Leche Colanta Entera 1.1L', 'Lácteos', 'Colanta', 'unidad', '1.1L'),
  ('Leche Colanta Entera 900ml', 'Lácteos', 'Colanta', 'unidad', '900ml'),
  ('Leche Colanta Deslactosada 1.1L', 'Lácteos', 'Colanta', 'unidad', '1.1L'),
  ('Leche Parmalat Entera 1L', 'Lácteos', 'Parmalat', 'unidad', '1L'),
  ('Leche Klim en Polvo 360g', 'Lácteos', 'Klim', 'kg', '360g'),
  ('Leche Klim en Polvo 900g', 'Lácteos', 'Klim', 'kg', '900g'),
  ('Leche Klim Bolsa 380g', 'Lácteos', 'Klim', 'kg', '380g'),
  ('Leche Nutrileche 1.1L', 'Lácteos', 'Nutrileche', 'unidad', '1.1L'),
  ('Yogurt Alpina Vaso Fresa 150g', 'Lácteos', 'Alpina', 'unidad', '150g'),
  ('Yogurt Alpina Vaso Fresa 1L', 'Lácteos', 'Alpina', 'unidad', '1L'),
  ('Yogurt Alpina Vaso Mora 150g', 'Lácteos', 'Alpina', 'unidad', '150g'),
  ('Yogurt Alquería Fresa 150g', 'Lácteos', 'Alquería', 'unidad', '150g'),
  ('Yogurt Alquería Fresa 1L', 'Lácteos', 'Alquería', 'unidad', '1L'),
  ('Yogurt Colanta Fresa 150g', 'Lácteos', 'Colanta', 'unidad', '150g'),
  ('Yogurt Colanta Fresa 1L', 'Lácteos', 'Colanta', 'unidad', '1L'),
  ('Kumis Alpina 1L', 'Lácteos', 'Alpina', 'unidad', '1L'),
  ('Kumis Alpina 200ml', 'Lácteos', 'Alpina', 'unidad', '200ml'),
  ('Kumis Alquería 1L', 'Lácteos', 'Alquería', 'unidad', '1L'),
  ('Kumis Colanta 1L', 'Lácteos', 'Colanta', 'unidad', '1L'),
  ('Bonyurt Fresa 150g', 'Lácteos', 'Fresa', 'unidad', '150g'),
  ('Yox Fresa 200g', 'Lácteos', 'Fresa', 'unidad', '200g'),
  ('Yogurt Griego Alpina 150g', 'Lácteos', 'Griego', 'unidad', '150g'),
  ('Arequipe Alpina 250g', 'Lácteos', 'Alpina', 'unidad', '250g'),
  ('Arequipe Alquería 250g', 'Lácteos', 'Alquería', 'unidad', '250g'),
  ('Queso Campesino Colanta 250g', 'Lácteos', 'Colanta', 'kg', '250g'),
  ('Queso Doble Crema Colanta 250g', 'Lácteos', 'Colanta', 'kg', '250g'),
  ('Queso Mozzarella Alpina 250g', 'Lácteos', 'Alpina', 'kg', '250g'),
  ('Queso Campesino Alquería 250g', 'Lácteos', 'Alquería', 'kg', '250g'),
  ('Mantequilla Colanta 250g', 'Lácteos', 'Colanta', 'unidad', '250g'),
  ('Mantequilla Alpina 250g', 'Lácteos', 'Alpina', 'unidad', '250g'),
  ('Margarina Rica 250g', 'Lácteos', 'Rica', 'unidad', '250g'),
  ('Crema de Leche Alpina 200ml', 'Lácteos', 'Alpina', 'unidad', '200ml'),
  ('Crema de Leche Alquería 200ml', 'Lácteos', 'Alquería', 'unidad', '200ml'),
  ('Avena Alpina en Hojuelas 500g', 'Lácteos', 'Alpina', 'kg', '500g'),
  ('Boggy Chocolate 90ml', 'Lácteos', 'Alpina', 'unidad', '90ml'),
  ('Finesse Fresa 130g', 'Lácteos', 'Alpina', 'unidad', '130g'),
  ('Papas Margarita Limón 27g', 'Snacks', 'Margarita', 'unidad', '27g'),
  ('Papas Margarita Limón 130g', 'Snacks', 'Margarita', 'unidad', '130g'),
  ('Papas Margarita Tradicional 27g', 'Snacks', 'Margarita', 'unidad', '27g'),
  ('Papas Margarita Tradicional 130g', 'Snacks', 'Margarita', 'unidad', '130g'),
  ('Papas Margarita BBQ 27g', 'Snacks', 'Margarita', 'unidad', '27g'),
  ('Papas Margarita BBQ 130g', 'Snacks', 'Margarita', 'unidad', '130g'),
  ('Papas Super Ricas Limón 27g', 'Snacks', 'Super', 'unidad', '27g'),
  ('Papas Super Ricas Limón 130g', 'Snacks', 'Super', 'unidad', '130g'),
  ('Papas Super Ricas Tradicional 27g', 'Snacks', 'Super', 'unidad', '27g'),
  ('Papas Super Ricas Tradicional 130g', 'Snacks', 'Super', 'unidad', '130g'),
  ('Papas Jack''s Tradicional 27g', 'Snacks', 'Jack''s', 'unidad', '27g'),
  ('Platanitos Margarita 27g', 'Snacks', 'Margarita', 'unidad', '27g'),
  ('Platanitos Margarita 130g', 'Snacks', 'Margarita', 'unidad', '130g'),
  ('Platanitos Super Ricas 27g', 'Snacks', 'Super', 'unidad', '27g'),
  ('Yucas Super Ricas 27g', 'Snacks', 'Super', 'unidad', '27g'),
  ('Detodito Original 30g', 'Snacks', 'Margarita', 'unidad', '30g'),
  ('Detodito Limón 30g', 'Snacks', 'Margarita', 'unidad', '30g'),
  ('Chitos 30g', 'Snacks', 'Margarita', 'unidad', '30g'),
  ('Doritos Nacho 30g', 'Snacks', 'Margarita', 'unidad', '30g'),
  ('Doritos Nacho 130g', 'Snacks', 'Margarita', 'unidad', '130g'),
  ('Doritos Queso 30g', 'Snacks', 'Margarita', 'unidad', '30g'),
  ('Chizitos 30g', 'Snacks', 'Margarita', 'unidad', '30g'),
  ('Cheese Tris 30g', 'Snacks', 'Margarita', 'unidad', '30g'),
  ('Ching''s 30g', 'Snacks', 'Margarita', 'unidad', '30g'),
  ('Chocolatina Jet 16g', 'Snacks', 'Nutresa', 'unidad', '16g'),
  ('Chocolatina Jumbo 23g', 'Snacks', 'Nutresa', 'unidad', '23g'),
  ('Choco Break 30g', 'Snacks', 'Nutresa', 'unidad', '30g'),
  ('Chocorramo 45g', 'Snacks', 'Ramo', 'unidad', '45g'),
  ('Nucita 25g', 'Snacks', 'Colombina', 'unidad', '25g'),
  ('Chocolatina Triángulo 25g', 'Snacks', 'Colombina', 'unidad', '25g'),
  ('Chocolisto Barra 30g', 'Snacks', 'Nutresa', 'unidad', '30g'),
  ('Cofrutti 18g', 'Snacks', 'Colombina', 'unidad', '18g'),
  ('Galletas Saltín Noel 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Saltín Noel 300g', 'Snacks', 'Noel', 'unidad', '300g'),
  ('Galletas Ducales 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Ducales 300g', 'Snacks', 'Noel', 'unidad', '300g'),
  ('Galletas Festival Chocolate 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Festival Vainilla 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Tosh Integral 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Wafer Noel Chocolate 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Cream Cracker 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Coco Lisa 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Ptú Noel 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Galletas María 27g', 'Snacks', 'Noel', 'unidad', '27g'),
  ('Galletas Chocmelo Noel 23g', 'Snacks', 'Noel', 'unidad', '23g'),
  ('Galletas Nucita Wafer 25g', 'Snacks', 'Noel', 'unidad', '25g'),
  ('Bon Bon Bum 1 unidad', 'Snacks', 'Colombina', 'unidad', '1 unidad'),
  ('Mentaditas 1 rollo', 'Snacks', 'Colombina', 'unidad', '1 rollo'),
  ('Frunas 1 unidad', 'Snacks', 'Colombina', 'unidad', '1 unidad'),
  ('Chicles Trident Menta 1 paquete', 'Snacks', 'Colombina', 'unidad', '1 paquete'),
  ('Chiclets Adams 1 paquete', 'Snacks', 'Colombina', 'unidad', '1 paquete'),
  ('Halls Mentol 1 rollo', 'Snacks', 'Colombina', 'unidad', '1 rollo'),
  ('Coffee Delight 1 rollo', 'Snacks', 'Colombina', 'unidad', '1 rollo'),
  ('Ping Pong 1 unidad', 'Snacks', 'Colombina', 'unidad', '1 unidad'),
  ('Colombina Rellenitos 1 unidad', 'Snacks', 'Colombina', 'unidad', '1 unidad'),
  ('Super Coco 1 unidad', 'Snacks', 'Colombina', 'unidad', '1 unidad'),
  ('Bocadillo Veleño', 'Snacks', 'Colombina', 'kg', '250g'),
  ('Panelitas de Leche 1 unidad', 'Snacks', 'Colombina', 'unidad', '1 unidad'),
  ('Maní Moto 40g', 'Snacks', 'Moto', 'unidad', '40g'),
  ('Maní Nutty 40g', 'Snacks', 'Nutty', 'unidad', '40g'),
  ('Uvas Pasas La Especial 40g', 'Snacks', 'La Especial', 'unidad', '40g'),
  ('Detergente Fab Polvo 250g', 'Aseo', 'Fab', 'kg', '250g'),
  ('Detergente Fab Polvo 1kg', 'Aseo', 'Fab', 'kg', '1kg'),
  ('Detergente Ariel Polvo 250g', 'Aseo', 'Ariel', 'kg', '250g'),
  ('Detergente Ariel Polvo 1kg', 'Aseo', 'Ariel', 'kg', '1kg'),
  ('Detergente Ace Polvo 250g', 'Aseo', 'Ace', 'kg', '250g'),
  ('Detergente Ace Polvo 1kg', 'Aseo', 'Ace', 'kg', '1kg'),
  ('Detergente Rey Polvo 250g', 'Aseo', 'Rey', 'kg', '250g'),
  ('Detergente Rey Polvo 1kg', 'Aseo', 'Rey', 'kg', '1kg'),
  ('Detergente Bolívar Polvo 250g', 'Aseo', 'Bolívar', 'kg', '250g'),
  ('Detergente Ariel Líquido 500ml', 'Aseo', 'Ariel', 'unidad', '500ml'),
  ('Detergente Ariel Líquido 1L', 'Aseo', 'Ariel', 'unidad', '1L'),
  ('Jabón Rey Barra 300g', 'Aseo', 'Rey', 'unidad', '300g'),
  ('Jabón Bonete Barra 300g', 'Aseo', 'Bonete', 'unidad', '300g'),
  ('Jabón Rica Blanca Barra 300g', 'Aseo', 'Rica Blanca', 'unidad', '300g'),
  ('Jabón Las Llaves Barra 300g', 'Aseo', 'Las Llaves', 'unidad', '300g'),
  ('Fabuloso Lavanda 500ml', 'Aseo', 'Fabuloso', 'unidad', '500ml'),
  ('Fabuloso Lavanda 1L', 'Aseo', 'Fabuloso', 'unidad', '1L'),
  ('Fabuloso Primavera 500ml', 'Aseo', 'Fabuloso', 'unidad', '500ml'),
  ('Fabuloso Primavera 1L', 'Aseo', 'Fabuloso', 'unidad', '1L'),
  ('Límpido Original 500ml', 'Aseo', 'Límpido', 'unidad', '500ml'),
  ('Límpido Original 1L', 'Aseo', 'Límpido', 'unidad', '1L'),
  ('Límpido Original 3L', 'Aseo', 'Límpido', 'unidad', '3L'),
  ('Blancox Original 500ml', 'Aseo', 'Blancox', 'unidad', '500ml'),
  ('Blancox Original 1L', 'Aseo', 'Blancox', 'unidad', '1L'),
  ('Varsol 500ml', 'Aseo', 'Varsol', 'unidad', '500ml'),
  ('Vanish Quitamanchas 450ml', 'Aseo', 'Vanish', 'unidad', '450ml'),
  ('Mistolín Multiusos 500ml', 'Aseo', 'Mistolín', 'unidad', '500ml'),
  ('Suavitel Suavizante 500ml', 'Aseo', 'Suavitel', 'unidad', '500ml'),
  ('Suavitel Suavizante 1L', 'Aseo', 'Suavitel', 'unidad', '1L'),
  ('Vim Limpiador Cremoso 500g', 'Aseo', 'Vim', 'kg', '500g'),
  ('Ajax Limpiador 500ml', 'Aseo', 'Ajax', 'unidad', '500ml'),
  ('Papel Higiénico Familia 4 rollos', 'Aseo', 'Familia', 'unidad', '4 rollos'),
  ('Papel Higiénico Familia 12 rollos', 'Aseo', 'Familia', 'unidad', '12 rollos'),
  ('Papel Higiénico Scott 4 rollos', 'Aseo', 'Scott', 'unidad', '4 rollos'),
  ('Papel Higiénico Suave 4 rollos', 'Aseo', 'Suave', 'unidad', '4 rollos'),
  ('Servilletas Familia 1 paquete', 'Aseo', 'Familia', 'unidad', '1 paquete'),
  ('Toallas Nosotras Clásica 1 paquete', 'Aseo', 'Nosotras', 'unidad', '1 paquete'),
  ('Toallas Nosotras Nocturna 1 paquete', 'Aseo', 'Nosotras', 'unidad', '1 paquete'),
  ('Pañales Pequeñin Etapa 3 1 paquete', 'Aseo', 'Pequeñin', 'unidad', '1 paquete'),
  ('Pañales Pequeñin Etapa 4 1 paquete', 'Aseo', 'Pequeñin', 'unidad', '1 paquete'),
  ('Pañitos Húmedos Familia 1 paquete', 'Aseo', 'Familia', 'unidad', '1 paquete'),
  ('Pañales Huggies Etapa 3 1 paquete', 'Aseo', 'Huggies', 'unidad', '1 paquete'),
  ('Jabón Protex 90g', 'Aseo', 'Protex', 'unidad', '90g'),
  ('Jabón Palmolive 90g', 'Aseo', 'Palmolive', 'unidad', '90g'),
  ('Jabón Dove 90g', 'Aseo', 'Dove', 'unidad', '90g'),
  ('Jabón Rexona 90g', 'Aseo', 'Rexona', 'unidad', '90g'),
  ('Champú Sedal Liso y Manejable 190ml', 'Aseo', 'Sedal', 'unidad', '190ml'),
  ('Champú Sedal Liso y Manejable 350ml', 'Aseo', 'Sedal', 'unidad', '350ml'),
  ('Champú Savital Sábila 190ml', 'Aseo', 'Savital', 'unidad', '190ml'),
  ('Champú Savital Sábila 350ml', 'Aseo', 'Savital', 'unidad', '350ml'),
  ('Champú Head & Shoulders 190ml', 'Aseo', 'Head & Shoulders', 'unidad', '190ml'),
  ('Crema Dental Colgate 75ml', 'Aseo', 'Colgate', 'unidad', '75ml'),
  ('Crema Dental Colgate 150ml', 'Aseo', 'Colgate', 'unidad', '150ml'),
  ('Crema Dental Kolynos 75ml', 'Aseo', 'Kolynos', 'unidad', '75ml'),
  ('Cepillo Dental Colgate 1 unidad', 'Aseo', 'Colgate', 'unidad', '1 unidad'),
  ('Desodorante Rexona Roll On 50ml', 'Aseo', 'Rexona', 'unidad', '50ml'),
  ('Desodorante Axe Spray 150ml', 'Aseo', 'Axe', 'unidad', '150ml'),
  ('Máquina de Afeitar Bic 1 unidad', 'Aseo', 'Bic', 'unidad', '1 unidad'),
  ('Espuma de Afeitar Gillette 200ml', 'Aseo', 'Gillette', 'unidad', '200ml'),
  ('Talco Para Pies Pom Pom 100g', 'Aseo', 'Pom Pom', 'unidad', '100g'),
  ('Crema Corporal Nivea 200ml', 'Aseo', 'Nivea', 'unidad', '200ml'),
  ('Enjuague Bucal Listerine 250ml', 'Aseo', 'Listerine', 'unidad', '250ml'),
  ('Algodón Facial 1 paquete', 'Aseo', 'Genérico', 'unidad', '1 paquete'),
  ('Copitos de Algodón 1 paquete', 'Aseo', 'Genérico', 'unidad', '1 paquete'),
  ('Toallitas Húmedas Íntimas 1 paquete', 'Aseo', 'Nosotras', 'unidad', '1 paquete'),
  ('Baygon Insecticida Aerosol', 'Aseo', 'Baygon', 'unidad', '360ml'),
  ('Baygon Trampa Cucarachas', 'Aseo', 'Baygon', 'unidad', '1 unidad'),
  ('Raid Insecticida Aerosol', 'Aseo', 'Raid', 'unidad', '360ml'),
  ('Ambientador Glade Aerosol', 'Aseo', 'Glade', 'unidad', '360ml'),
  ('Ambientador Air Wick', 'Aseo', 'Air Wick', 'unidad', '1 unidad'),
  ('Bolsas de Basura Familia', 'Aseo', 'Familia', 'unidad', '1 rollo'),
  ('Esponjilla Brillo', 'Aseo', 'Brillo', 'unidad', '1 unidad'),
  ('Escoba Plástica', 'Aseo', 'Genérico', 'unidad', '1 unidad'),
  ('Trapero', 'Aseo', 'Genérico', 'unidad', '1 unidad'),
  ('Guantes de Aseo Látex', 'Aseo', 'Genérico', 'unidad', '1 par'),
  ('Fósforos de Cocina', 'Aseo', 'El Rey', 'unidad', '1 caja'),
  ('Vela de Parafina', 'Aseo', 'Genérico', 'unidad', '1 unidad'),
  ('Lavaloza Axion', 'Aseo', 'Axion', 'unidad', '250g'),
  ('Lavaloza Ola', 'Aseo', 'Ola', 'unidad', '500ml'),
  ('Lavaloza Limón Ola', 'Aseo', 'Ola', 'unidad', '250g'),
  ('Pan Tajado Blanco Bimbo', 'Panadería', 'Bimbo', 'unidad', '1 paquete'),
  ('Pan Tajado Integral Bimbo', 'Panadería', 'Bimbo', 'unidad', '1 paquete'),
  ('Pan Perro Bimbo', 'Panadería', 'Bimbo', 'unidad', '1 paquete'),
  ('Pan Hamburguesa Bimbo', 'Panadería', 'Bimbo', 'unidad', '1 paquete'),
  ('Pony Pan Bimbo', 'Panadería', 'Bimbo', 'unidad', '1 paquete'),
  ('Ponqué Ramo', 'Panadería', 'Ramo', 'unidad', '1 unidad'),
  ('Gansito Ramo', 'Panadería', 'Ramo', 'unidad', '1 unidad'),
  ('Chocoramo', 'Panadería', 'Ramo', 'unidad', '1 unidad'),
  ('Ponqué Gala', 'Panadería', 'Gala', 'unidad', '1 unidad'),
  ('Pan Aliñado', 'Panadería', 'Genérico', 'unidad', '1 unidad'),
  ('Tostadas Bimbo', 'Panadería', 'Bimbo', 'unidad', '1 paquete'),
  ('Arepa de Maíz Blanco', 'Panadería', 'Doña Arepa', 'unidad', '1 paquete'),
  ('Arepa de Maíz Amarillo', 'Panadería', 'Doña Arepa', 'unidad', '1 paquete'),
  ('Arepa Boyacense', 'Panadería', 'Doña Arepa', 'unidad', '1 paquete'),
  ('Pan Campesino', 'Panadería', 'Genérico', 'unidad', '1 unidad'),
  ('Buñuelo Congelado', 'Panadería', 'Genérico', 'unidad', '1 paquete'),
  ('Pandebono Congelado', 'Panadería', 'Genérico', 'unidad', '1 paquete'),
  ('Mogolla Integral', 'Panadería', 'Genérico', 'unidad', '1 unidad'),
  ('Palito de Queso', 'Panadería', 'Genérico', 'unidad', '1 unidad'),
  ('Croissant', 'Panadería', 'Bimbo', 'unidad', '1 unidad'),
  ('Salchicha Zenú Ranchera 500g', 'Carnes', 'Zenú', 'kg', '500g'),
  ('Salchicha Zenú Tipo Viena 500g', 'Carnes', 'Zenú', 'kg', '500g'),
  ('Salchicha Rica Ranchera 500g', 'Carnes', 'Rica', 'kg', '500g'),
  ('Salchichón Zenú 250g', 'Carnes', 'Zenú', 'kg', '250g'),
  ('Mortadela Zenú 250g', 'Carnes', 'Zenú', 'kg', '250g'),
  ('Mortadela Zenú 500g', 'Carnes', 'Zenú', 'kg', '500g'),
  ('Mortadela Rica 250g', 'Carnes', 'Rica', 'kg', '250g'),
  ('Chorizo Zenú Antioqueño 500g', 'Carnes', 'Zenú', 'kg', '500g'),
  ('Chorizo Ranchero 500g', 'Carnes', 'Ranchera', 'kg', '500g'),
  ('Chorizo Santarrosano 500g', 'Carnes', 'Zenú', 'kg', '500g'),
  ('Jamón Zenú 250g', 'Carnes', 'Zenú', 'kg', '250g'),
  ('Jamón Suizo 250g', 'Carnes', 'Suizo', 'kg', '250g'),
  ('Jamonada Zenú 250g', 'Carnes', 'Zenú', 'kg', '250g'),
  ('Butifarra Rica 500g', 'Carnes', 'Rica', 'kg', '500g'),
  ('Longaniza 500g', 'Carnes', 'Zenú', 'kg', '500g'),
  ('Tocineta Zenú 250g', 'Carnes', 'Zenú', 'kg', '250g'),
  ('Salchichas Viena Rica 500g', 'Carnes', 'Rica', 'kg', '500g'),
  ('Carne Molida de Res 500g', 'Carnes', 'Genérico', 'kg', '500g'),
  ('Pechuga de Pollo 1kg', 'Carnes', 'Genérico', 'kg', '1kg'),
  ('Pollo Entero', 'Carnes', 'Genérico', 'unidad', '1 unidad'),
  ('Costilla de Cerdo 1kg', 'Carnes', 'Genérico', 'kg', '1kg'),
  ('Carne de Res para Asar 1kg', 'Carnes', 'Genérico', 'kg', '1kg'),
  ('Chuleta de Cerdo 1kg', 'Carnes', 'Genérico', 'kg', '1kg'),
  ('Vísceras de Pollo (Menudencia) 500g', 'Carnes', 'Genérico', 'kg', '500g'),
  ('Morcilla 500g', 'Carnes', 'Genérico', 'kg', '500g'),
  ('Chicharrón 500g', 'Carnes', 'Genérico', 'kg', '500g'),
  ('Arroz Diana 500g', 'Granos y abarrotes', 'Diana', 'kg', '500g'),
  ('Arroz Diana 1kg', 'Granos y abarrotes', 'Diana', 'kg', '1kg'),
  ('Arroz Diana 3kg', 'Granos y abarrotes', 'Diana', 'kg', '3kg'),
  ('Arroz Roa 500g', 'Granos y abarrotes', 'Roa', 'kg', '500g'),
  ('Arroz Roa 1kg', 'Granos y abarrotes', 'Roa', 'kg', '1kg'),
  ('Arroz Roa 3kg', 'Granos y abarrotes', 'Roa', 'kg', '3kg'),
  ('Arroz Doña Pepa 500g', 'Granos y abarrotes', 'Doña Pepa', 'kg', '500g'),
  ('Arroz Doña Pepa 1kg', 'Granos y abarrotes', 'Doña Pepa', 'kg', '1kg'),
  ('Arroz Florhuila 500g', 'Granos y abarrotes', 'Florhuila', 'kg', '500g'),
  ('Arroz Florhuila 1kg', 'Granos y abarrotes', 'Florhuila', 'kg', '1kg'),
  ('Arroz Blanquita 1kg', 'Granos y abarrotes', 'Blanquita', 'kg', '1kg'),
  ('Aceite Gourmet 500ml', 'Granos y abarrotes', 'Gourmet', 'litro', '500ml'),
  ('Aceite Gourmet 1L', 'Granos y abarrotes', 'Gourmet', 'litro', '1L'),
  ('Aceite Gourmet 3L', 'Granos y abarrotes', 'Gourmet', 'litro', '3L'),
  ('Aceite Premier 500ml', 'Granos y abarrotes', 'Premier', 'litro', '500ml'),
  ('Aceite Premier 1L', 'Granos y abarrotes', 'Premier', 'litro', '1L'),
  ('Aceite Girasol Del Llano 500ml', 'Granos y abarrotes', 'Del Llano', 'litro', '500ml'),
  ('Aceite Girasol Del Llano 1L', 'Granos y abarrotes', 'Del Llano', 'litro', '1L'),
  ('Aceite Oliosoya 1L', 'Granos y abarrotes', 'Oliosoya', 'litro', '1L'),
  ('Aceite La Fina 500ml', 'Granos y abarrotes', 'La Fina', 'litro', '500ml'),
  ('Aceite La Fina 1L', 'Granos y abarrotes', 'La Fina', 'litro', '1L'),
  ('Manteca Vegetal Familia 500g', 'Granos y abarrotes', 'Familia', 'kg', '500g'),
  ('Azúcar Manuelita 1kg', 'Granos y abarrotes', 'Manuelita', 'kg', '1kg'),
  ('Azúcar Manuelita 500g', 'Granos y abarrotes', 'Manuelita', 'kg', '500g'),
  ('Azúcar Incauca 1kg', 'Granos y abarrotes', 'Incauca', 'kg', '1kg'),
  ('Azúcar Morena Manuelita 500g', 'Granos y abarrotes', 'Manuelita', 'kg', '500g'),
  ('Panela Redonda', 'Granos y abarrotes', 'Genérico', 'kg', '1 unidad (500g)'),
  ('Panela Cuadrada', 'Granos y abarrotes', 'Genérico', 'kg', '1 unidad (500g)'),
  ('Panela Pulverizada Doña Panela', 'Granos y abarrotes', 'Doña Panela', 'kg', '500g'),
  ('Sal Refisal 500g', 'Granos y abarrotes', 'Refisal', 'kg', '500g'),
  ('Sal Refisal 1kg', 'Granos y abarrotes', 'Refisal', 'kg', '1kg'),
  ('Sal Marina La Sal', 'Granos y abarrotes', 'La Sal', 'kg', '500g'),
  ('Café Sello Rojo 250g', 'Granos y abarrotes', 'Sello Rojo', 'kg', '250g'),
  ('Café Sello Rojo 500g', 'Granos y abarrotes', 'Sello Rojo', 'kg', '500g'),
  ('Café Águila Roja 250g', 'Granos y abarrotes', 'Águila Roja', 'kg', '250g'),
  ('Café Águila Roja 500g', 'Granos y abarrotes', 'Águila Roja', 'kg', '500g'),
  ('Café Juan Valdez 250g', 'Granos y abarrotes', 'Juan Valdez', 'kg', '250g'),
  ('Café La Bastilla 250g', 'Granos y abarrotes', 'La Bastilla', 'kg', '250g'),
  ('Café Matiz 250g', 'Granos y abarrotes', 'Matiz', 'kg', '250g'),
  ('Tinto Colcafé 1 sobre', 'Granos y abarrotes', 'Colcafé', 'unidad', '1 sobre'),
  ('Tinto Colcafé 170g', 'Granos y abarrotes', 'Colcafé', 'kg', '170g'),
  ('Chocolate Luker Mesa 250g', 'Granos y abarrotes', 'Luker', 'kg', '250g'),
  ('Chocolate Luker Mesa 500g', 'Granos y abarrotes', 'Luker', 'kg', '500g'),
  ('Chocolate Corona 250g', 'Granos y abarrotes', 'Corona', 'kg', '250g'),
  ('Chocolate Corona 500g', 'Granos y abarrotes', 'Corona', 'kg', '500g'),
  ('Chocolate Rey 250g', 'Granos y abarrotes', 'Rey', 'kg', '250g'),
  ('Chocolisto en Polvo 400g', 'Granos y abarrotes', 'Chocolisto', 'kg', '400g'),
  ('Milo en Polvo 400g', 'Granos y abarrotes', 'Milo', 'kg', '400g'),
  ('Pasta La Muñeca Espagueti 250g', 'Granos y abarrotes', 'La Muñeca', 'kg', '250g'),
  ('Pasta La Muñeca Espagueti 500g', 'Granos y abarrotes', 'La Muñeca', 'kg', '500g'),
  ('Pasta Doria Espagueti 250g', 'Granos y abarrotes', 'Doria', 'kg', '250g'),
  ('Pasta Doria Espagueti 500g', 'Granos y abarrotes', 'Doria', 'kg', '500g'),
  ('Pasta Doria Corbatines 250g', 'Granos y abarrotes', 'Doria', 'kg', '250g'),
  ('Pasta Zenú Macarrones 250g', 'Granos y abarrotes', 'Zenú', 'kg', '250g'),
  ('Fríjol Cargamanto 500g', 'Granos y abarrotes', 'Genérico', 'kg', '500g'),
  ('Fríjol Cargamanto 1kg', 'Granos y abarrotes', 'Genérico', 'kg', '1kg'),
  ('Fríjol Bola Roja 500g', 'Granos y abarrotes', 'Genérico', 'kg', '500g'),
  ('Lenteja 500g', 'Granos y abarrotes', 'Genérico', 'kg', '500g'),
  ('Garbanzo 500g', 'Granos y abarrotes', 'Genérico', 'kg', '500g'),
  ('Arveja Verde Seca 500g', 'Granos y abarrotes', 'Genérico', 'kg', '500g'),
  ('Maíz Trillado 500g', 'Granos y abarrotes', 'Genérico', 'kg', '500g'),
  ('Maíz Pira (Palomitas) 250g', 'Granos y abarrotes', 'Genérico', 'kg', '250g'),
  ('Avena en Hojuelas Quaker 500g', 'Granos y abarrotes', 'Quaker', 'kg', '500g'),
  ('Harina de Trigo Haz de Oros 500g', 'Granos y abarrotes', 'Haz de Oros', 'kg', '500g'),
  ('Harina de Trigo Haz de Oros 1kg', 'Granos y abarrotes', 'Haz de Oros', 'kg', '1kg'),
  ('Harina PAN Blanca 500g', 'Granos y abarrotes', 'PAN', 'kg', '500g'),
  ('Harina PAN Blanca 1kg', 'Granos y abarrotes', 'PAN', 'kg', '1kg'),
  ('Harina PAN Amarilla 500g', 'Granos y abarrotes', 'PAN', 'kg', '500g'),
  ('Fécula de Maíz Maizena 250g', 'Granos y abarrotes', 'Maizena', 'kg', '250g'),
  ('Atún Van Camps en Aceite 160g', 'Granos y abarrotes', 'Van Camps', 'kg', '160g'),
  ('Atún Van Camps en Agua 160g', 'Granos y abarrotes', 'Van Camps', 'kg', '160g'),
  ('Atún Isabel 160g', 'Granos y abarrotes', 'Isabel', 'kg', '160g'),
  ('Sardinas Cunda en Tomate 425g', 'Granos y abarrotes', 'Cunda', 'kg', '425g'),
  ('Sardinas Duque en Tomate 155g', 'Granos y abarrotes', 'Duque', 'kg', '155g'),
  ('Salchichas Enlatadas Ranchera 300g', 'Granos y abarrotes', 'Rica', 'kg', '300g'),
  ('Maíz Tierno Enlatado Del Valle 300g', 'Granos y abarrotes', 'Del Valle', 'kg', '300g'),
  ('Arveja Enlatada La Constancia 300g', 'Granos y abarrotes', 'La Constancia', 'kg', '300g'),
  ('Champiñones Enlatados 200g', 'Granos y abarrotes', 'Genérico', 'kg', '200g'),
  ('Salsa de Tomate Fruco 200g', 'Granos y abarrotes', 'Fruco', 'kg', '200g'),
  ('Salsa de Tomate Fruco 400g', 'Granos y abarrotes', 'Fruco', 'kg', '400g'),
  ('Mayonesa Fruco 200g', 'Granos y abarrotes', 'Fruco', 'kg', '200g'),
  ('Mayonesa Fruco 400g', 'Granos y abarrotes', 'Fruco', 'kg', '400g'),
  ('Mostaza Fruco 200g', 'Granos y abarrotes', 'Fruco', 'kg', '200g'),
  ('Salsa Rosada Fruco 200g', 'Granos y abarrotes', 'Fruco', 'kg', '200g'),
  ('Salsa de Tomate Todo Rico 200g', 'Granos y abarrotes', 'Todo Rico', 'kg', '200g'),
  ('Mayonesa Todo Rico 200g', 'Granos y abarrotes', 'Todo Rico', 'kg', '200g'),
  ('Salsa Piña Fruco 200g', 'Granos y abarrotes', 'Fruco', 'kg', '200g'),
  ('Consomé de Gallina Maggi 1 sobre', 'Granos y abarrotes', 'Maggi', 'unidad', '1 sobre'),
  ('Consomé de Gallina Maggi 100g', 'Granos y abarrotes', 'Maggi', 'kg', '100g'),
  ('Ajo Sal La Constancia 100g', 'Granos y abarrotes', 'La Constancia', 'kg', '100g'),
  ('Color Refisal (Achiote) 100g', 'Granos y abarrotes', 'Refisal', 'kg', '100g'),
  ('Comino Molido 50g', 'Granos y abarrotes', 'Genérico', 'kg', '50g'),
  ('Pimienta Negra Molida 50g', 'Granos y abarrotes', 'Genérico', 'kg', '50g'),
  ('Adobo Completo Doña Gallina 100g', 'Granos y abarrotes', 'Doña Gallina', 'kg', '100g'),
  ('Sazonador Todo en Uno Maggi 100g', 'Granos y abarrotes', 'Maggi', 'kg', '100g'),
  ('Vinagre Blanco 500ml', 'Granos y abarrotes', 'Genérico', 'litro', '500ml'),
  ('Leche Condensada La Lechera 400g', 'Granos y abarrotes', 'La Lechera', 'kg', '400g'),
  ('Leche Evaporada Klim 400g', 'Granos y abarrotes', 'Klim', 'kg', '400g'),
  ('Gelatina Royal Fresa 40g', 'Granos y abarrotes', 'Royal', 'unidad', '40g'),
  ('Gelatina Royal Limón 40g', 'Granos y abarrotes', 'Royal', 'unidad', '40g'),
  ('Flan Royal Vainilla 60g', 'Granos y abarrotes', 'Royal', 'unidad', '60g'),
  ('Levadura Royal 10g', 'Granos y abarrotes', 'Royal', 'unidad', '10g'),
  ('Polvo de Hornear Royal 100g', 'Granos y abarrotes', 'Royal', 'kg', '100g'),
  ('Vinagre de Manzana 500ml', 'Granos y abarrotes', 'Genérico', 'litro', '500ml'),
  ('Miel de Abejas 250g', 'Granos y abarrotes', 'Genérico', 'kg', '250g'),
  ('Cigarrillos Marlboro Rojo Cajetilla', 'Cigarrería', 'Marlboro', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Marlboro Rojo Paquete', 'Cigarrería', 'Marlboro', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Marlboro Gold Cajetilla', 'Cigarrería', 'Marlboro', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Marlboro Gold Paquete', 'Cigarrería', 'Marlboro', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Mustang Rojo Cajetilla', 'Cigarrería', 'Mustang', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Mustang Rojo Paquete', 'Cigarrería', 'Mustang', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Mustang Azul Cajetilla', 'Cigarrería', 'Mustang', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Mustang Azul Paquete', 'Cigarrería', 'Mustang', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Boston Cajetilla', 'Cigarrería', 'Boston', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Boston Paquete', 'Cigarrería', 'Boston', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Caribe Cajetilla', 'Cigarrería', 'Caribe', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Caribe Paquete', 'Cigarrería', 'Caribe', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos L&M Rojo Cajetilla', 'Cigarrería', 'L&M', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos L&M Rojo Paquete', 'Cigarrería', 'L&M', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos L&M Azul Cajetilla', 'Cigarrería', 'L&M', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos L&M Azul Paquete', 'Cigarrería', 'L&M', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Kool Cajetilla', 'Cigarrería', 'Kool', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Kool Paquete', 'Cigarrería', 'Kool', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Pielroja Cajetilla', 'Cigarrería', 'Pielroja', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Pielroja Paquete', 'Cigarrería', 'Pielroja', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Lucky Strike Cajetilla', 'Cigarrería', 'Lucky Strike', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Lucky Strike Paquete', 'Cigarrería', 'Lucky Strike', 'unidad', '1 paquete (10 cajetillas)'),
  ('Cigarrillos Chesterfield Cajetilla', 'Cigarrería', 'Chesterfield', 'unidad', '1 cajetilla (20 unidades)'),
  ('Cigarrillos Chesterfield Paquete', 'Cigarrería', 'Chesterfield', 'unidad', '1 paquete (10 cajetillas)'),
  ('Fósforos El Rey', 'Cigarrería', 'El Rey', 'unidad', '1 caja'),
  ('Encendedor Bic', 'Cigarrería', 'Bic', 'unidad', '1 unidad'),
  ('Encendedor Genérico', 'Cigarrería', 'Genérico', 'unidad', '1 unidad'),
  ('Papel para Armar Cigarrillos', 'Cigarrería', 'Genérico', 'unidad', '1 paquete'),
  ('Chicle de Nicotina', 'Cigarrería', 'Genérico', 'unidad', '1 unidad'),
  ('Huevo AAA Rojo', 'Huevos', 'Genérico', 'unidad', 'Cubeta x30'),
  ('Huevo AA Rojo', 'Huevos', 'Genérico', 'unidad', 'Cubeta x30'),
  ('Huevo A Rojo', 'Huevos', 'Genérico', 'unidad', 'Cubeta x30'),
  ('Huevo AAA Blanco', 'Huevos', 'Genérico', 'unidad', 'Cubeta x30'),
  ('Huevo A Blanco', 'Huevos', 'Genérico', 'unidad', 'Cubeta x30'),
  ('Huevo Campesino', 'Huevos', 'Genérico', 'unidad', 'Cubeta x30'),
  ('Huevo Kevin''s AAA', 'Huevos', 'Kevin''s', 'unidad', 'Cubeta x30'),
  ('Huevo Santa Reyes AAA', 'Huevos', 'Santa Reyes', 'unidad', 'Cubeta x30'),
  ('Huevo Oro Rojo AAA', 'Huevos', 'Oro', 'unidad', 'Cubeta x30'),
  ('Huevo Codorniz', 'Huevos', 'Genérico', 'unidad', 'Bandeja x18'),
  ('Papa Pastusa', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Papa Criolla', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Papa R-12', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Cebolla Cabezona Blanca', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Cebolla Cabezona Roja', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Cebolla Larga (Junca)', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Tomate Chonto', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Tomate Riñón', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Plátano Verde', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Plátano Maduro', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Limón Tahití', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Limón Común', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Aguacate Hass', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Aguacate Común', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Zanahoria', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Repollo Blanco', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Repollo Morado', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Banano', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Yuca', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Ahuyama', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Pepino Cohombro', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Habichuela', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Arveja Verde Fresca', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Cilantro', 'Verduras y frutas', 'Genérico', 'unidad', 'A granel'),
  ('Perejil', 'Verduras y frutas', 'Genérico', 'unidad', 'A granel'),
  ('Ajo', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Pimentón Rojo', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Pimentón Verde', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Lechuga Batavia', 'Verduras y frutas', 'Genérico', 'unidad', 'A granel'),
  ('Espinaca', 'Verduras y frutas', 'Genérico', 'unidad', 'A granel'),
  ('Naranja', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Mandarina', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Mango de Azúcar', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Piña Gold', 'Verduras y frutas', 'Genérico', 'unidad', 'A granel'),
  ('Papaya Hawaiana', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Sandía', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Melón', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Fresa', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Mora de Castilla', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Maracuyá', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Guayaba', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Uva Verde', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Manzana Roja', 'Verduras y frutas', 'Genérico', 'kg', 'A granel'),
  ('Pera', 'Verduras y frutas', 'Genérico', 'kg', 'A granel')
) as seed(nombre, categoria, marca, unidad_base, presentacion)
where pm.nombre = seed.nombre
  and pm.categoria = seed.categoria
  and pm.marca = seed.marca
  and pm.unidad_base = seed.unidad_base
  and pm.presentacion = seed.presentacion;
